# FaultTreeAnalysis & MentoCarlo

## 加载python库

  加载相应的第三方库，
  包括  
  
  - numpy 数组库、  
  - scipy 科学计算库、  
  - matplotlib 绘图库、  
  
另外 蒙特卡罗法要大量使用随机数 所以专门加载 numpy中的random 库  

In [26]:
import numpy as np 
import scipy as sp
#import pandas as pd #目前用不上
import matplotlib.pyplot as plt
import numpy.random as random

## 设定仿真次数，设备的总运行时间以及最小单位里程

In [27]:
TimeMax = 1000000
IntervalTimes = 10000
del_t = TimeMax / IntervalTimes
t = [i* del_t for i in range(1,IntervalTimes,1)]

In [28]:
#选一万次仿真
Ns = 10000

## 随机抽样产生各个部分的失效时间

In [30]:
T1 = random.random((Ns,1))
T2 = random.random((Ns,1))
T3 = random.random((Ns,1))
T4 = random.random((Ns,1))
T5 = random.random((Ns,1))
T6 = random.random((Ns,1))
T7 = random.random((Ns,1))
T8 = random.random((Ns,1))
T9 = random.random((Ns,1))
T10 = random.random((Ns,1))
T11 = random.random((Ns,1))
T = np.array([T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11])
print T

[[[ 0.34321572]
  [ 0.25653058]
  [ 0.35530869]
  ..., 
  [ 0.00378582]
  [ 0.55281476]
  [ 0.41077411]]

 [[ 0.05201813]
  [ 0.43961613]
  [ 0.27254712]
  ..., 
  [ 0.15830603]
  [ 0.02123972]
  [ 0.61243013]]

 [[ 0.9682247 ]
  [ 0.3924102 ]
  [ 0.44141025]
  ..., 
  [ 0.86284897]
  [ 0.47263472]
  [ 0.35006051]]

 ..., 
 [[ 0.38078228]
  [ 0.17639269]
  [ 0.03925149]
  ..., 
  [ 0.84305651]
  [ 0.39103456]
  [ 0.01152557]]

 [[ 0.95187229]
  [ 0.67182268]
  [ 0.07494548]
  ..., 
  [ 0.38081954]
  [ 0.79434092]
  [ 0.53616714]]

 [[ 0.62584385]
  [ 0.9664775 ]
  [ 0.16209814]
  ..., 
  [ 0.44517616]
  [ 0.27563008]
  [ 0.86591963]]]


In [19]:
NUM = np.zeros((Ns,11))
tk = np.zeros((1,Ns))

In [20]:
for L in range(Ns):
    tt = T[:,L]
    ttf = np.sort(T[:,L].T).T
    Z = np.zeros((1,11))
    for i in range(0,10):
        for j in range(0,10):
            if ttf[j] == tt[i]:
                Z[:,i] = 1
                tk[0, L] = ttf[j]
                break
        PHA = Z[:,1]+Z[:,2]+Z[:,3]+Z[:,4]+Z[:,5]+Z[:,6]+Z[:,7]+Z[:,8]+Z[:,9]+Z[:,10]+Z[:,0]
        if PHA == 1:
            NUM[L,i] = NUM[L, i] + 1
            break

In [24]:
delete = 0
for i in range(Ns):
    if tk [0,i] > TimeMax:
        delete = delete + 1
deta_m = np.zeros((1, IntervalTimes))
for n in range(Ns):
    if tk[0,n] <= t[1]:
        deta_m[0,0] = deta_m[0,0]+1
    for r in range(2,Ns):
        if tk[0,n] > t[r-1] and tk[0,n] <= t(r):
            deta_m[0,r] = deta[0,r]+1

[[ 10000.      0.      0. ...,      0.      0.      0.]]


In [31]:
m = []
deta_l = np.tolist( deta_m [0])
print deta_l
#for i in range(1,IntervalTimes):
#    m[i] = np.sum(deta_m[0,i])
#m = np.array(m)
#F = m/Ns
#R = 1-F
#print m

AttributeError: 'module' object has no attribute 'tolist'

# 好惨。。。只编到这里，实在是编不下去了。